#!/usr/bin/env bash
# Script to display all active IPv4 IP addresses on the current machine

# Use ifconfig to get network interface information and extract IPv4 addresses
ifconfig | grep -oP 'inet \K[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'